"""Prompts package."""
from nexus_agent.prompts.templates import (
    AUTONOMOUS_OPTIMIZER_SYSTEM_PROMPT,
    DEVELOPER_SYSTEM_PROMPT,
    TECHNICAL_ARCHITECT_SYSTEM_PROMPT,
)

__all__ = [
    "TECHNICAL_ARCHITECT_SYSTEM_PROMPT",
    "DEVELOPER_SYSTEM_PROMPT",
    "AUTONOMOUS_OPTIMIZER_SYSTEM_PROMPT",
]
